ARG BASE_IMAGE="ghcr.io/ducttape-lab/server-base"
ARG BASE_VERSION="latest"

FROM ${BASE_IMAGE}:${BASE_VERSION}

COPY assets/forgejo-folders.service /etc/systemd/system/

RUN dnf install -y git git-lfs openssh-server \
    && dnf clean all \
    && rm -rf /var/cache/yum \
    && curl -fsSL https://codeberg.org/forgejo/forgejo/releases/download/v15.0.3/forgejo-15.0.3-linux-amd64 -o /usr/local/bin/forgejo \
    && chmod +x /usr/local/bin/forgejo \
    && curl -fsSL https://codeberg.org/forgejo/forgejo/raw/branch/forgejo/contrib/systemd/forgejo.service -o /etc/systemd/system/forgejo.service \
    && sed -i 's/HOME=\/home\/git/HOME=\/var\/home\/git/' /etc/systemd/system/forgejo.service \
    && (restorecon /etc/systemd/system/forgejo-folders.service 2>/dev/null || :) \
    && systemctl enable forgejo.service \
    && systemctl enable forgejo-folders.service \
    && systemctl enable sshd.service \
    && chmod 640 /etc/shadow \
    && mkdir -p /var/home/ \
    && groupadd --system git \
    && useradd --system --shell /bin/bash --comment 'Git Version Control' --gid git --home-dir /var/home/git --create-home git \
    && mkdir /var/lib/forgejo \
    && chown git:git /var/lib/forgejo \
    && chmod 750 /var/lib/forgejo \
    && mkdir /etc/forgejo \
    && chown root:git /etc/forgejo \
    && chmod 770 /etc/forgejo
